openapi: 3.0.0
info:
  title: Catitionary API
  description: '猫の名前の自動生成を支援するCatitionaryのAPI'
  version: 0.1.0
servers:
  - url: 'http://127.0.0.1:9001/api'
    description: 'ローカル環境'
  - url: 'http://127.0.0.1:4010'
    description: 'PRISM'
paths:
  /names:
    $ref: '../paths/names/index.yml'
  /names/patterns:
    $ref: '../paths/names/patterns.yml'
  /cat/types:
    $ref: '../paths/cat/types.yml'
  /cat/characterics:
    $ref: '../paths/cat/characterics.yml'

# /name/series -> シリーズを指定してその中から名前を返す()

tags:
  - name: names
    description: 名前関連
  - name: types
    description: 種類関連
